name: Capture build history and write to csv

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Append build history
    runs-on: ubuntu-22.04

    steps:

    # checkout build-history repo
    - uses: actions/checkout@v3
      with:
        repository: 'medic/build-history'
        path: 'build-history'
    # checkout build-history-data repo
    - uses: actions/checkout@v3
      with:
        repository: 'medic/build-history-data'
        path: 'build-history-data'
    - name: Append file size
      run: echo "`date +%s`,`stat -c "%s" ./build-history/index.html`" >> ./build-history-data/build-history/filesize.csv
    - name: Commit & Push build history
      run: cd build-history-data && git add . && git push https://garethbowen:${{ secrets.BUILD_HISTORY_DATA_PUSH_TOKEN }}@github.com/medic/build-history-data.git
