name: Capture build history and write to csv

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Append build history
    runs-on: ubuntu-22.04
    env:
      BUILD_DATA_TOKEN: ${{ secrets.BUILD_HISTORY_DATA_PUSH_TOKEN }}

    steps:

    # checkout build-history repo
    - uses: actions/checkout@v3
      with:
        repository: 'medic/build-history'
        path: 'build-history'
    # checkout build-history-data repo
    - uses: actions/checkout@v3
      with:
        repository: 'medic/build-history-data'
        path: 'build-history-data'
    - name: Append file size
      run: echo "`date +%s`,`stat -c "%s" ./build-history/index.html`" >> ./build-history-data/build-history/filesize.csv
    - name: Commit & Push build history
      uses: actions-js/push@master
      with:
        github_token: ${{ env.BUILD_DATA_TOKEN }}
        directory: 'build-history-data'
        repository: 'medic/build-history-data'
