name: Capture build history and write to csv

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**' # don't run if the data changes as that would cause an infinite loop

jobs:
  build:
    name: Append build history
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'medic/build-history'
        path: 'build-history'
    - name: Append file size
      run: echo "`date +%s`,`stat -c "%s" ./build-history/index.html`" >> ./build-history/data/build-history/filesize.csv
    - name: Commit & Push build history
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: 'build-history'
