name: Capture build history and write to csv

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**' # don't run if the data changes as that would cause an infinite loop

jobs:
  build:
    name: Build for Node version ${{ matrix.node-version }}
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Append file size
      run: echo "`date +%s`,`stat -c "%s" ${{ env.home }}/index.html`" >> ${{ env.home }}/data/build-history/filesize.csv
